# Generated by Django 4.2.23 on 2026-05-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='waterbody',
            name='maps_waterb_org_id_385bc0_idx',
        ),
        migrations.AddField(
            model_name='waterbody',
            name='external_source',
            field=models.CharField(blank=True, help_text='Exempel: "viss"', max_length=64),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='geometry_source',
            field=models.CharField(blank=True, help_text='Exempel: "viss_arcgis_layer_56"', max_length=128),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='source_name',
            field=models.CharField(blank=True, help_text='Officiellt namn från källan', max_length=255),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='viss_eu_cd',
            field=models.CharField(blank=True, db_index=True, help_text='VISS EU_CD', max_length=64),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='viss_ms_cd',
            field=models.CharField(blank=True, db_index=True, help_text='VISS MS_CD / waterpublicid', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='waterbody',
            constraint=models.UniqueConstraint(condition=models.Q(('viss_ms_cd', ''), _negated=True), fields=('org', 'viss_ms_cd'), name='unique_waterbody_org_viss_ms_cd'),
        ),
    ]
