# Generated by Django 4.2.23 on 2026-05-31 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditevent_id_alter_membership_id_and_more'),
        ('maps', '0002_remove_waterbody_maps_waterb_org_id_385bc0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBodyHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eco_status', models.CharField(blank=True, max_length=255)),
                ('chem_status', models.CharField(blank=True, max_length=255)),
                ('risk', models.TextField(blank=True)),
                ('mkn', models.TextField(blank=True)),
                ('fish', models.CharField(blank=True, max_length=255)),
                ('eco_tone', models.CharField(choices=[('good', 'God'), ('moderate', 'Måttlig'), ('bad', 'Dålig'), ('neutral', 'Neutral')], default='neutral', max_length=16)),
                ('chem_tone', models.CharField(choices=[('good', 'God'), ('moderate', 'Måttlig'), ('bad', 'Dålig'), ('neutral', 'Neutral')], default='neutral', max_length=16)),
                ('fish_tone', models.CharField(choices=[('good', 'God'), ('moderate', 'Måttlig'), ('bad', 'Dålig'), ('neutral', 'Neutral')], default='neutral', max_length=16)),
                ('risk_flag', models.BooleanField(default=False)),
                ('source', models.CharField(default='VISS', max_length=64)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('fetch_error', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.organization')),
                ('water_body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshot', to='maps.waterbody')),
            ],
        ),
        migrations.AddConstraint(
            model_name='waterbodyhealthsnapshot',
            constraint=models.UniqueConstraint(fields=('org', 'water_body'), name='unique_health_snapshot_org_water_body'),
        ),
    ]
