# Generated by Django 6.0.2 on 2026-02-16 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.organization')),
            ],
            options={
                'ordering': ['designation'],
                'unique_together': {('org', 'designation')},
            },
        ),
        migrations.CreateModel(
            name='RightHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_holders', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('org', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FishingRightShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=6, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_right_shares', to='core.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='fishingrights.property')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='fishingrights.rightholder')),
            ],
            options={
                'ordering': ['property__designation', 'holder__name'],
                'unique_together': {('org', 'property', 'holder')},
            },
        ),
    ]
