# Generated by Django 6.0.2 on 2026-04-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('geojson', models.JSONField()),
                ('status', models.CharField(default='needs_action', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['org'], name='fisheries_a_org_id_ee0510_idx')],
            },
        ),
    ]
