# Generated by Django 6.0.2 on 2026-04-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionarea',
            name='status',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('needs_action', 'Needs action'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='needs_action', max_length=50),
        ),
    ]
