# Generated by Django 6.0.2 on 2026-04-20 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditevent'),
        ('fisheries', '0004_actionarea_actual_cost_actionarea_deadline_and_more'),
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('fish_stock', 'Fish stock'), ('habitat', 'Habitat'), ('water_quality', 'Water quality'), ('illegal_fishing', 'Illegal fishing'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('linked_to_action', 'Linked to action'), ('closed', 'Closed')], default='new', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_observations', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_observations', to=settings.AUTH_USER_MODEL)),
                ('water_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='maps.waterbody')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['org'], name='fisheries_o_org_id_5fb750_idx')],
            },
        ),
    ]
