# Generated by Django 6.0.2 on 2026-04-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheries', '0005_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='linked_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='fisheries.actionarea'),
        ),
    ]
