# Generated by Django 4.2.23 on 2026-05-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheries', '0007_observationlog_observationcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='category',
            field=models.CharField(choices=[('fish_stock', 'Fiskbestånd'), ('habitat', 'Biotop & habitat'), ('water_quality', 'Vattenkvalitet'), ('illegal_fishing', 'Misstänkt tjuvfiske'), ('infrastructure', 'Anläggning & infrastruktur'), ('fish_death', 'Fiskdöd'), ('environment', 'Miljö & nedskräpning'), ('water_level', 'Vattennivå / erosion'), ('member_suggestion', 'Förslag från medlem'), ('needs_action', 'Behöver beslut'), ('other', 'Övrigt')], default='other', max_length=50),
        ),
    ]
