# Generated by Django 4.2.23 on 2026-05-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisheries', '0008_alter_observation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionarea',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude/WGS84 for exact map position.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='actionarea',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude/WGS84 for exact map position.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude/WGS84 for exact map position.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude/WGS84 for exact map position.', max_digits=9, null=True),
        ),
    ]
