# Generated by Django 4.2.23 on 2026-05-31 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fisheries', '0009_actionarea_latitude_actionarea_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionarea',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when moved to trash; null means active.', null=True),
        ),
        migrations.AddField(
            model_name='actionarea',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when moved to trash; null means active.', null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_observations', to=settings.AUTH_USER_MODEL),
        ),
    ]
