# Generated by Django 4.2.23 on 2026-06-02 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fisheries.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_auditevent_id_alter_membership_id_and_more'),
        ('fisheries', '0010_soft_delete_trash'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisheriesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=fisheries.models.fisheries_image_upload_to)),
                ('caption', models.TextField(blank=True)),
                ('image_type', models.CharField(choices=[('before', 'Före'), ('progress', 'Pågående'), ('after', 'Efter')], max_length=20)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fisheries.actionarea')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fisheries.actioncomment')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fisheries.observation')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_fisheries_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['org'], name='fisheries_f_org_id_93d238_idx')],
            },
        ),
    ]
