# Generated by Django 6.0.2 on 2026-03-20 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_deleted_at_document_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('protocol', 'Protokoll'), ('bylaws', 'Stadgar'), ('notice', 'Kallelse'), ('motion', 'Motion'), ('decision', 'Beslut'), ('other', 'Övrigt')], default='other', max_length=30)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('uploaded', 'Uppladdat'), ('template', 'Mallbaserat')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Skapad'), ('version_added', 'Ny version'), ('updated', 'Uppdaterad'), ('deleted', 'Borttagen'), ('restored', 'Återställd')], max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttemplate'),
        ),
    ]
