# Generated by Django 6.0.2 on 2026-03-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documenttemplate_document_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('meeting', 'Stämmoprotokoll'), ('protocol', 'Protokoll'), ('bylaws', 'Stadgar'), ('notice', 'Kallelse'), ('motion', 'Motion'), ('decision', 'Beslut'), ('other', 'Övrigt')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='category',
            field=models.CharField(choices=[('meeting', 'Stämmoprotokoll'), ('protocol', 'Protokoll'), ('bylaws', 'Stadgar'), ('notice', 'Kallelse'), ('motion', 'Motion'), ('decision', 'Beslut'), ('other', 'Övrigt')], default='other', max_length=30),
        ),
    ]
