# Generated by Django 6.0.2 on 2026-03-28 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Utkast'), ('locked_for_review', 'Låst för justering'), ('under_review', 'Under justering'), ('approved', 'Godkänt'), ('finalized', 'Avslutat')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('protocol', 'Protokoll'), ('bylaws', 'Stadgar'), ('notice', 'Kallelse'), ('motion', 'Motion'), ('decision', 'Beslut'), ('other', 'Övrigt')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='category',
            field=models.CharField(choices=[('protocol', 'Protokoll'), ('bylaws', 'Stadgar'), ('notice', 'Kallelse'), ('motion', 'Motion'), ('decision', 'Beslut'), ('other', 'Övrigt')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Väntar'), ('approved', 'Godkänd'), ('changes_requested', 'Ändringar begärda')], default='pending', max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents.document')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('document', 'reviewer')},
            },
        ),
    ]
