# Generated by Django 6.0.2 on 2026-03-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_locked_at_document_locked_by_and_more'),
        ('governance', '0012_alter_governanceactivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='governance.meeting'),
        ),
    ]
