# Generated by Django 6.0.2 on 2026-03-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_documentsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
