# Generated by Django 4.2.23 on 2026-05-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditevent"),
        ("documents", "0011_document_document_hash"),
        ("governance", "0014_meeting_chairperson_meeting_secretary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_system_folder", models.BooleanField(default=False)),
                (
                    "folder_type",
                    models.CharField(
                        choices=[
                            ("archive_root", "Arkiv"),
                            ("year", "År"),
                            ("month", "Månad"),
                            ("meeting_group", "Möteskategori"),
                            ("static", "Systemmapp"),
                            ("custom", "Anpassad"),
                        ],
                        default="custom",
                        max_length=40,
                    ),
                ),
                (
                    "system_key",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("meeting_type", models.CharField(blank=True, max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_folders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="core.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="documents.documentfolder",
                    ),
                ),
                (
                    "related_meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_folders",
                        to="governance.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.documentfolder",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="folder_auto_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="documentfolder",
            index=models.Index(
                fields=["org", "parent"],
                name="documents_d_org_id_fa0f65_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentfolder",
            index=models.Index(
                fields=["org", "folder_type"],
                name="documents_d_org_id_c17edb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentfolder",
            index=models.Index(
                fields=["org", "system_key"],
                name="documents_d_org_id_cd5de4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentfolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_system_folder", True)),
                fields=("org", "system_key"),
                name="uniq_document_folder_system_key_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentfolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_system_folder", False)),
                fields=("org", "parent", "name"),
                name="uniq_document_folder_name_per_parent_org",
            ),
        ),
    ]
