# Generated by Django 6.0.2 on 2026-04-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
        ('governance', '0014_meeting_chairperson_meeting_secretary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='governance.meeting'),
        ),
    ]
