# Generated by Django 6.0.2 on 2026-03-24 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chair', 'Ordförande'), ('secretary', 'Sekreterare'), ('treasurer', 'Kassör'), ('member', 'Ledamot'), ('deputy', 'Suppleant')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('can_manage_matters', models.BooleanField(default=False)),
                ('can_manage_documents', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'user__email'],
                'unique_together': {('org', 'user')},
            },
        ),
    ]
