# Generated by Django 6.0.2 on 2026-03-26 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditevent'),
        ('governance', '0002_governanceactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('motion', 'Motion'), ('case', 'Ärende'), ('information', 'Information')], default='case', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Inkommen'), ('in_preparation', 'Under beredning'), ('ready_for_proposal', 'Klar för styrelseförslag'), ('ready_for_meeting', 'Klar för stämma'), ('decided', 'Beslutad'), ('closed', 'Avslutad')], default='received', max_length=30)),
                ('board_comment', models.TextField(blank=True)),
                ('prepared_statement', models.TextField(blank=True)),
                ('ready_for_meeting', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_matters', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.organization')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_matters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
