# Generated by Django 6.0.2 on 2026-03-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_boardmatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceactivitylog',
            name='action',
            field=models.CharField(choices=[('member_created', 'Styrelsemedlem skapad'), ('member_updated', 'Styrelsemedlem uppdaterad'), ('member_deleted', 'Styrelsemedlem borttagen'), ('permission_changed', 'Behörighet ändrad'), ('login_access', 'Åtkomst till governance'), ('matter_created', 'Ärende skapat'), ('matter_updated', 'Ärende uppdaterat'), ('matter_status_changed', 'Ärendestatus ändrad')], max_length=50),
        ),
    ]
