# Generated by Django 6.0.2 on 2026-03-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmatter',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='governance.meeting'),
        ),
    ]
