# Generated by Django 6.0.2 on 2026-03-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0008_alter_governanceactivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
