# Generated by Django 6.0.2 on 2026-03-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0009_meeting_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_links', to='governance.boardmatter')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_matters', to='governance.meeting')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('meeting', 'matter')},
            },
        ),
    ]
