# Generated by Django 6.0.2 on 2026-03-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0010_meetingmatter'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmatter',
            name='decision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardmatter',
            name='meeting_decision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='boardmatter',
            name='status',
            field=models.CharField(choices=[('received', 'Inkommen'), ('in_preparation', 'Under beredning'), ('ready_for_proposal', 'Klar för styrelseförslag'), ('ready_for_meeting', 'Klar för stämma'), ('handled_in_meeting', 'Behandlad i stämma'), ('decided', 'Beslutad'), ('closed', 'Avslutad')], default='received', max_length=30),
        ),
    ]
