# Generated by Django 6.0.2 on 2026-03-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0011_boardmatter_decision_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceactivitylog',
            name='action',
            field=models.CharField(choices=[('member_created', 'Styrelsemedlem skapad'), ('member_updated', 'Styrelsemedlem uppdaterad'), ('member_deleted', 'Styrelsemedlem borttagen'), ('permission_changed', 'Behörighet ändrad'), ('login_access', 'Åtkomst till governance'), ('matter_created', 'Ärende skapat'), ('matter_updated', 'Ärende uppdaterat'), ('matter_status_changed', 'Ärendestatus ändrad'), ('matter_handled_in_meeting', 'Ärende behandlat i stämma'), ('meeting_created', 'Stämma skapad'), ('meeting_updated', 'Stämma uppdaterad')], max_length=50),
        ),
    ]
