# Generated by Django 6.0.2 on 2026-03-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0012_alter_governanceactivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Pågående'), ('closed', 'Avslutat')], default='ongoing', max_length=20),
        ),
    ]
